# Generated by Django 2.0.8 on 2018-12-18 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20181016_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
