# Generated by Django 2.0.8 on 2018-12-27 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20181227_2240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venue',
            old_name='rating',
            new_name='wifi_rating',
        ),
    ]
