# Generated by Django 2.0.8 on 2019-04-29 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190217_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
