# Generated by Django 2.0.8 on 2019-05-30 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_venue_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='slogan',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
