# Generated by Django 2.0.8 on 2019-10-07 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20190625_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='food_rating',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='food', to='core.Rating'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='wifi_rating',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wifi', to='core.Rating'),
        ),
    ]
