# Generated by Django 2.0.8 on 2019-10-07 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20191007_1833'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venue',
            old_name='food_rating',
            new_name='food',
        ),
        migrations.RenameField(
            model_name='venue',
            old_name='wifi_rating',
            new_name='wifi',
        ),
        migrations.AddField(
            model_name='venue',
            name='atmoshere',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='atmosphere', to='core.Rating'),
        ),
        migrations.AddField(
            model_name='venue',
            name='coffee',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coffee', to='core.Rating'),
        ),
        migrations.AddField(
            model_name='venue',
            name='sockets',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sockets', to='core.Rating'),
        ),
    ]
