# Generated by Django 2.0.8 on 2019-10-07 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20191007_1848'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venue',
            old_name='atmoshere',
            new_name='atmosphere',
        ),
    ]
