# Generated by Django 2.2.10 on 2020-05-22 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20191007_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='image',
            field=models.URLField(null=True),
        ),
    ]
