# Generated by Django 2.2.10 on 2020-05-22 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_venue_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='image',
        ),
    ]
