# Generated by Django 2.2.16 on 2020-09-05 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_ratingsrefactor'),
        ('core', '0017_auto_20200721_2240'),
    ]

    operations = [
    ]
