# Generated by Django 2.2.20 on 2021-05-15 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_merge_20200905_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='uploaded_image',
            field=models.FileField(null=True, upload_to='venue-images'),
        ),
    ]
