# Generated by Django 2.2.16 on 2020-10-03 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_merge_20200905_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='image',
            field=models.FileField(null=True, upload_to='venue-images'),
        ),
    ]
