# Generated by Django 2.2.16 on 2021-04-11 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20201003_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='uploaded_image',
            field=models.FileField(null=True, upload_to='venue-images'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='image',
            field=models.URLField(null=True),
        ),
    ]
